### ISSUE TITLE
Unable to upload brave-bin, onlyoffice-bin and davinci resolve

### ISSUE THREAD

**Issue by ghost** [Shastra-OS/shastrarepo#5]
Hey, I was unable to upload some packages.
They are in large size.
So how you will able to provide them?

**Comment by vivekpal1** [comment]
You cannot upload file size over 25 on Github
Thats why I created [shastrarepo](https://gitlab.com/shastraos/shastrarepo) on GitLab
You can push all those big package there.

And I'll surely archiving this repository
